global:
  resolve_timeout: 5m
  smtp_require_tls: false
  smtp_smarthost: xxxxx
  smtp_auth_username: xxxxx
  smtp_auth_password: xxxxx
  smtp_from: xxxxx
templates:
  - /etc/alertmanager/config/*.tmpl
inhibit_rules:
  - equal:
      - namespace
      - alertname
    target_match:
      severity_re: warning|info
    source_match:
      severity: critical
  - equal:
      - namespace
      - alertname
    target_match:
      severity_re: info
    source_match:
      severity: warning
receivers:
  - name: Default
    email_configs:
      - to: xxxxx
        send_resolved: true
route:
  group_by:
    - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: Default
  repeat_interval: 1h
  routes: []
