apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: "2021-12-16T07:00:58Z"
  generation: 1
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 1.2.2
    prometheus: k8s
    role: alert-rules
  name: node-exporter-rules
  namespace: monitoring
  resourceVersion: "3721501"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/kuboard/prometheusrules/node-exporter-rules
  uid: 692671ac-e2c7-4584-b5c2-6ce032e3d337
spec:
  groups:
  - name: node-exporter
    rules:
    - alert: NodeFilesystemSpaceFillingUp
      annotations:
        description: 节点 {{ $labels.instance }} 上磁盘 {{ $labels.device }} 的文件系统只剩下 {{
          printf "%.2f" $value }}% 剩余空间，并且即将耗尽。
        description_en: Filesystem on {{ $labels.device }} at {{ $labels.instance
          }} has only {{ printf "%.2f" $value }}% available space left and is filling
          up.
        summary: 磁盘空间将在 24 小时内耗尽
        summary_en: Filesystem is predicted to run out of space within the next 24
          hours.
      expr: |
        (
          node_filesystem_avail_bytes{job="node-exporter",fstype!=""} / node_filesystem_size_bytes{job="node-exporter",fstype!=""} * 100 < 40
        and
          predict_linear(node_filesystem_avail_bytes{job="node-exporter",fstype!=""}[6h], 24*60*60) < 0
        and
          node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
        )
      for: 30m
      labels:
        severity: warning
    - alert: NodeFilesystemSpaceFillingUp
      annotations:
        description: 节点 {{ $labels.instance }} 上磁盘 {{ $labels.device }} 的文件系统只剩下 {{
          printf "%.2f" $value }}% 剩余空间，并且马上将要耗尽。
        description_en: Filesystem on {{ $labels.device }} at {{ $labels.instance
          }} has only {{ printf "%.2f" $value }}% available space left and is filling
          up.
        summary: 磁盘空间将在 4 小时内耗尽
        summary_en: Filesystem is predicted to run out of space within the next 4
          hours.
      expr: |
        (
          node_filesystem_avail_bytes{job="node-exporter",fstype!=""} / node_filesystem_size_bytes{job="node-exporter",fstype!=""} * 100 < 15
        and
          predict_linear(node_filesystem_avail_bytes{job="node-exporter",fstype!=""}[6h], 4*60*60) < 0
        and
          node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
        )
      for: 1h
      labels:
        severity: critical
    - alert: NodeFilesystemAlmostOutOfSpace
      annotations:
        description: 节点 {{ $labels.instance }} 上磁盘 {{ $labels.device }} 的文件系统只剩下 {{
          printf "%.2f" $value }}% 剩余空间。
        description_en: Filesystem on {{ $labels.device }} at {{ $labels.instance
          }} has only {{ printf "%.2f" $value }}% available space left.
        summary: 剩余磁盘空间不足 5%。
        summary_en: Filesystem has less than 5% space left.
      expr: |
        (
          node_filesystem_avail_bytes{job="node-exporter",fstype!=""} / node_filesystem_size_bytes{job="node-exporter",fstype!=""} * 100 < 5
        and
          node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
        )
      for: 30m
      labels:
        severity: warning
    - alert: NodeFilesystemAlmostOutOfSpace
      annotations:
        description: 节点 {{ $labels.instance }} 上磁盘 {{ $labels.device }} 的文件系统只剩下 {{
          printf "%.2f" $value }}% 剩余空间。
        description_en: Filesystem on {{ $labels.device }} at {{ $labels.instance
          }} has only {{ printf "%.2f" $value }}% available space left.
        summary: 剩余磁盘空间不足 3%。
        summary_en: Filesystem has less than 3% space left.
      expr: |
        (
          node_filesystem_avail_bytes{job="node-exporter",fstype!=""} / node_filesystem_size_bytes{job="node-exporter",fstype!=""} * 100 < 3
        and
          node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
        )
      for: 1h
      labels:
        severity: critical
    - alert: NodeFilesystemFilesFillingUp
      annotations:
        description: 节点 {{ $labels.instance }} 上磁盘 {{ $labels.device }} 的文件系统只剩下 {{
          printf "%.2f" $value }}% 可用的 inodes，并且即将耗尽。
        description_en: Filesystem on {{ $labels.device }} at {{ $labels.instance
          }} has only {{ printf "%.2f" $value }}% available inodes left and is filling
          up.
        summary: 预计文件系统将在 24 小时内耗尽 inodes。
        summary_en: Filesystem is predicted to run out of inodes within the next 24
          hours.
      expr: |
        (
          node_filesystem_files_free{job="node-exporter",fstype!=""} / node_filesystem_files{job="node-exporter",fstype!=""} * 100 < 40
        and
          predict_linear(node_filesystem_files_free{job="node-exporter",fstype!=""}[6h], 24*60*60) < 0
        and
          node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
        )
      for: 1h
      labels:
        severity: warning
    - alert: NodeFilesystemFilesFillingUp
      annotations:
        description: 节点 {{ $labels.instance }} 上磁盘 {{ $labels.device }} 的文件系统只剩下 {{
          printf "%.2f" $value }}% 可用的 inodes，并且即将耗尽。
        description_en: Filesystem on {{ $labels.device }} at {{ $labels.instance
          }} has only {{ printf "%.2f" $value }}% available inodes left and is filling
          up fast.
        summary: 预计文件系统将在 4 小时内耗尽 inodes。
        summary_en: Filesystem is predicted to run out of inodes within the next 4
          hours.
      expr: |
        (
          node_filesystem_files_free{job="node-exporter",fstype!=""} / node_filesystem_files{job="node-exporter",fstype!=""} * 100 < 20
        and
          predict_linear(node_filesystem_files_free{job="node-exporter",fstype!=""}[6h], 4*60*60) < 0
        and
          node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
        )
      for: 1h
      labels:
        severity: critical
    - alert: NodeFilesystemAlmostOutOfFiles
      annotations:
        description: 节点 {{ $labels.instance }} 上磁盘 {{ $labels.device }} 的文件系统只剩下 {{
          printf "%.2f" $value }}% 可用的 inodes。
        description_en: Filesystem on {{ $labels.device }} at {{ $labels.instance
          }} has only {{ printf "%.2f" $value }}% available inodes left.
        summary: 文件系统剩余 inodes 不足 5%。
        summary_en: Filesystem has less than 5% inodes left.
      expr: |
        (
          node_filesystem_files_free{job="node-exporter",fstype!=""} / node_filesystem_files{job="node-exporter",fstype!=""} * 100 < 5
        and
          node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
        )
      for: 1h
      labels:
        severity: warning
    - alert: NodeFilesystemAlmostOutOfFiles
      annotations:
        description: 节点 {{ $labels.instance }} 上磁盘 {{ $labels.device }} 的文件系统只剩下 {{
          printf "%.2f" $value }}% 可用的 inodes。
        description_en: Filesystem on {{ $labels.device }} at {{ $labels.instance
          }} has only {{ printf "%.2f" $value }}% available inodes left.
        summary: 文件系统剩余 inodes 不足 3%。
        summary_en: Filesystem has less than 3% inodes left.
      expr: |
        (
          node_filesystem_files_free{job="node-exporter",fstype!=""} / node_filesystem_files{job="node-exporter",fstype!=""} * 100 < 3
        and
          node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
        )
      for: 1h
      labels:
        severity: critical
    - alert: NodeNetworkReceiveErrs
      annotations:
        description: 节点 {{ $labels.instance }} 上网络接口 {{ $labels.device }} 在过去 2 分钟内出现了
          {{ printf "%.0f" $value }} 次接收错误。
        description_en: '{{ $labels.instance }} interface {{ $labels.device }} has
          encountered {{ printf "%.0f" $value }} receive errors in the last two minutes.'
        summary: 网络接口出现了许多的接收错误。
        summary_en: Network interface is reporting many receive errors.
      expr: |
        rate(node_network_receive_errs_total[2m]) / rate(node_network_receive_packets_total[2m]) > 0.01
      for: 1h
      labels:
        severity: warning
    - alert: NodeNetworkTransmitErrs
      annotations:
        description: 节点 {{ $labels.instance }} 上网络接口 {{ $labels.device }} 在过去 2 分钟内出现了
          {{ printf "%.0f" $value }} 次传送错误。
        description_en: '{{ $labels.instance }} interface {{ $labels.device }} has
          encountered {{ printf "%.0f" $value }} transmit errors in the last two minutes.'
        summary: 网络接口出现了许多的传送错误。
        summary_en: Network interface is reporting many transmit errors.
      expr: |
        rate(node_network_transmit_errs_total[2m]) / rate(node_network_transmit_packets_total[2m]) > 0.01
      for: 1h
      labels:
        severity: warning
    - alert: NodeHighNumberConntrackEntriesUsed
      annotations:
        description: '{{ $value | humanizePercentage }} 的连接记录已被使用。'
        description_en: '{{ $value | humanizePercentage }} of conntrack entries are
          used.'
        summary: 连接记录数已接近极限。
        summary_en: Number of conntrack are getting close to the limit.
      expr: |
        (node_nf_conntrack_entries / node_nf_conntrack_entries_limit) > 0.75
      labels:
        severity: warning
    - alert: NodeTextFileCollectorScrapeError
      annotations:
        description: Node Exporter 的文本采集器刷新失败。
        summary: Node Exporter text file collector failed to scrape.
      expr: |
        node_textfile_scrape_error{job="node-exporter"} == 1
      labels:
        severity: warning
    - alert: NodeClockSkewDetected
      annotations:
        description: 节点 {{ $labels.instance }} 出现超过 300 秒的时钟偏移。请确保该节点上的 NTP 配置正确。
        description_en: Clock on {{ $labels.instance }} is out of sync by more than
          300s. Ensure NTP is configured correctly on this host.
        summary: 出现时钟偏移。
        summary_en: Clock skew detected.
      expr: |
        (
          node_timex_offset_seconds > 0.05
        and
          deriv(node_timex_offset_seconds[5m]) >= 0
        )
        or
        (
          node_timex_offset_seconds < -0.05
        and
          deriv(node_timex_offset_seconds[5m]) <= 0
        )
      for: 10m
      labels:
        severity: warning
    - alert: NodeClockNotSynchronising
      annotations:
        description: 节点 {{ $labels.instance }} 上的时钟不同步。请确保该节点的 NTP 配置正确。
        description_en: Clock on {{ $labels.instance }} is not synchronising. Ensure
          NTP is configured on this host.
        summary: 时钟未同步。
        summary_en: Clock not synchronising.
      expr: |
        min_over_time(node_timex_sync_status[5m]) == 0
        and
        node_timex_maxerror_seconds >= 16
      for: 10m
      labels:
        severity: warning
    - alert: NodeRAIDDegraded
      annotations:
        description: 节点 {{ $labels.instance }} 上的磁盘阵列 '{{ $labels.device }}' 由于一个或更多的磁盘出现故障，处于降级状态。剩余的磁盘驱动器不足以自动修复故障。
        description_en: RAID array '{{ $labels.device }}' on {{ $labels.instance }}
          is in degraded state due to one or more disks failures. Number of spare
          drives is insufficient to fix issue automatically.
        summary: 磁盘阵列被降级。
        summary_en: RAID Array is degraded
      expr: |
        node_md_disks_required - ignoring (state) (node_md_disks{state="active"}) > 0
      for: 15m
      labels:
        severity: critical
    - alert: NodeRAIDDiskFailure
      annotations:
        description: 节点 {{ $labels.instance }} 上磁盘阵列 '{{ $labels.device }}' 中至少有一个磁盘出现故障，请及时更换故障磁盘。
        description_en: At least one device in RAID array on {{ $labels.instance }}
          failed. Array '{{ $labels.device }}' needs attention and possibly a disk
          swap.
        summary: 磁盘阵列出现故障。
        summary_en: Failed device in RAID array
      expr: |
        node_md_disks{state="failed"} > 0
      labels:
        severity: warning
    - alert: NodeFileDescriptorLimit
      annotations:
        description: File descriptors limit at {{ $labels.instance }} is currently
          at {{ printf "%.2f" $value }}%.
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodefiledescriptorlimit
        summary: Kernel is predicted to exhaust file descriptors limit soon.
      expr: |
        (
          node_filefd_allocated{job="node-exporter"} * 100 / node_filefd_maximum{job="node-exporter"} > 70
        )
      for: 15m
      labels:
        severity: warning
    - alert: NodeFileDescriptorLimit
      annotations:
        description: File descriptors limit at {{ $labels.instance }} is currently
          at {{ printf "%.2f" $value }}%.
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/node/nodefiledescriptorlimit
        summary: Kernel is predicted to exhaust file descriptors limit soon.
      expr: |
        (
          node_filefd_allocated{job="node-exporter"} * 100 / node_filefd_maximum{job="node-exporter"} > 90
        )
      for: 15m
      labels:
        severity: critical
  - name: node-exporter.rules
    rules:
    - expr: |
        count without (cpu) (
          count without (mode) (
            node_cpu_seconds_total{job="node-exporter"}
          )
        )
      record: instance:node_num_cpu:sum
    - expr: |
        1 - avg without (cpu, mode) (
          rate(node_cpu_seconds_total{job="node-exporter", mode="idle"}[5m])
        )
      record: instance:node_cpu_utilisation:rate5m
    - expr: |
        (
          node_load1{job="node-exporter"}
        /
          instance:node_num_cpu:sum{job="node-exporter"}
        )
      record: instance:node_load1_per_cpu:ratio
    - expr: |
        1 - (
          node_memory_MemAvailable_bytes{job="node-exporter"}
        /
          node_memory_MemTotal_bytes{job="node-exporter"}
        )
      record: instance:node_memory_utilisation:ratio
    - expr: |
        rate(node_vmstat_pgmajfault{job="node-exporter"}[5m])
      record: instance:node_vmstat_pgmajfault:rate5m
    - expr: |
        rate(node_disk_io_time_seconds_total{job="node-exporter", device=~"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+"}[5m])
      record: instance_device:node_disk_io_time_seconds:rate5m
    - expr: |
        rate(node_disk_io_time_weighted_seconds_total{job="node-exporter", device=~"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+"}[5m])
      record: instance_device:node_disk_io_time_weighted_seconds:rate5m
    - expr: |
        sum without (device) (
          rate(node_network_receive_bytes_total{job="node-exporter", device!="lo"}[5m])
        )
      record: instance:node_network_receive_bytes_excluding_lo:rate5m
    - expr: |
        sum without (device) (
          rate(node_network_transmit_bytes_total{job="node-exporter", device!="lo"}[5m])
        )
      record: instance:node_network_transmit_bytes_excluding_lo:rate5m
    - expr: |
        sum without (device) (
          rate(node_network_receive_drop_total{job="node-exporter", device!="lo"}[5m])
        )
      record: instance:node_network_receive_drop_excluding_lo:rate5m
    - expr: |
        sum without (device) (
          rate(node_network_transmit_drop_total{job="node-exporter", device!="lo"}[5m])
        )
      record: instance:node_network_transmit_drop_excluding_lo:rate5m
